version: "3.9"
services:
  db:
    image: postgres:16
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce
      POSTGRES_DB: ecommerce
    ports:
      - "5440:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
